SET @SARTHARION_BASE_HEALTH:= 550;
SET @DRAGONS_BASE_HEALTH:= 160;
SET @SARTHARION_25:= 31311;
SET @DRAGON1:= 31535;
SET @DRAGON2:= 31520;
SET @DRAGON3:= 31534;

UPDATE `creature_template` SET `health_mod` = @SARTHARION_BASE_HEALTH + (@SARTHARION_BASE_HEALTH * 0.4) WHERE `entry` = @SARTHARION_25;
UPDATE `creature_template` SET `health_mod` = @DRAGONS_BASE_HEALTH + (@DRAGONS_BASE_HEALTH * 0.3) WHERE `entry` IN (@DRAGON1, @DRAGON2, @DRAGON3);
