#ifndef DEF_AHNKAHET_H
#define DEF_AHNKAHET_H

#define DATA_ELDER_NADOX			1
#define DATA_PRINCE_TALDARAM		2
#define DATA_JEDOGA_SHADOWSEEKER	3
#define DATA_HERALD_VOLAZJ		  4
#define DATA_AMANITAR			   5

#define DATA_ELDER_NADOX_EVENT		  6
#define DATA_PRINCE_TALDARAM_EVENT	  7
#define DATA_JEDOGA_SHADOWSEEKER_EVENT  8
#define DATA_HERALD_VOLAZJ_EVENT		9
#define DATA_AMANITAR_EVENT			 10

#define DATA_SPHERE1					11
#define DATA_SPHERE2					12
#define DATA_SPHERE1_EVENT			  13
#define DATA_SPHERE2_EVENT			  14
#define DATA_PRINCE_TALDARAM_PLATFORM   15

#endif
