UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'additem';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'combatstop';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'cooldown';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'demorph';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'die';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'distance';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'freeze';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gm chat';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gmnameannounce';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'go creature';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gobject activate';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'gobject delete';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gobject near';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'gobject add temp';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gobject';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'summon';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'groupsummon';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'guild create';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'guild delete';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'guild uninvite';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'kick';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'learn all gm';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'learn';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'list creature';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup creature';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup faction';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup item';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'announce';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'aura';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ban account';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ban';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'baninfo account';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'baninfo';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'character reputation';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'mute';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup player account';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup player email';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup player ip';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup quest';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup spell';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify bit';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify energy';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify hp';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify mana';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify mount';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify phase';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify rage';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'modify runicpower';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'character titles';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'npc follow stop';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'npc info';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'npc follow';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'npc delete';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'npc';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'pet unlearn';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'tele name';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket assign';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket close';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'gmunstuck';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket comment';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket list';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket onlinelist';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket unassign';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket viewid';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket viewname';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'unaura';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'unban ip';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'unfreeze';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'unlearn';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'whispers';
UPDATE `db_feronis_world`.`command` SET `security` = '4' WHERE `command`.`name` = 'wp event';
UPDATE `db_feronis_world`.`command` SET `security` = '4' WHERE `command`.`name` = 'wp load';
UPDATE `db_feronis_world`.`command` SET `security` = '4' WHERE `command`.`name` = 'wp show';
UPDATE `db_feronis_world`.`command` SET `security` = '4' WHERE `command`.`name` = 'wp unload';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'titles remove';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'titles add';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'titles set mask';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'character changefaction';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'character changerace';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'achievement add';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'achievement';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'npc add temp';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'morph';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'lfg player';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'lfg queue';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'skirmish';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'achievement checkall';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'lookup player';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'lfg';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'character customize';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'instance';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'list';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'playall';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'possess';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'quest complete';
UPDATE `db_feronis_world`.`command` SET `security` = '3' WHERE `command`.`name` = 'quest remove';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'recall';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'respawn';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'revive';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'send mail';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'ticket delete';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'pinfo';
UPDATE `db_feronis_world`.`command` SET `security` = '4' WHERE `command`.`name` = 'pet';
UPDATE `db_feronis_world`.`command` SET `security` = '100' WHERE `command`.`name` = 'reset spells';
UPDATE `db_feronis_world`.`command` SET `security` = '100' WHERE `command`.`name` = 'reset stats';
UPDATE `db_feronis_world`.`command` SET `security` = '100' WHERE `command`.`name` = 'reset level';
UPDATE `db_feronis_world`.`command` SET `security` = '100' WHERE `command`.`name` = 'reset honor';
INSERT INTO `db_feronis_world`.`command` (`name`, `security`, `help`) VALUES ('ticket response', '1', NULL);
INSERT INTO `db_feronis_world`.`command` (`name`, `security`, `help`) VALUES ('ticket response append', '1', NULL);
INSERT INTO `db_feronis_world`.`command` (`name`, `security`, `help`) VALUES ('ticket response appendln', '1', NULL);
INSERT INTO `db_feronis_world`.`command` (`name`, `security`, `help`) VALUES ('ticket response complete', '1', NULL);
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'gobject add temp';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'quest add';
UPDATE `db_feronis_world`.`command` SET `security` = '2' WHERE `command`.`name` = 'quest complete';
UPDATE `db_feronis_world`.`command` SET `security` = '1' WHERE `command`.`name` = 'character reputation';