/* SARTHARION */
SET @SARTHARION_BASE_HEALTH:= 550;
SET @DRAGONS_BASE_HEALTH:= 160;
SET @SARTHARION_25:= 31311;
SET @DRAGON1:= 31535;
SET @DRAGON2:= 31520;
SET @DRAGON3:= 31534;

UPDATE `creature_template` SET `health_mod` = @SARTHARION_BASE_HEALTH + (@SARTHARION_BASE_HEALTH * 0) WHERE `entry` = @SARTHARION_25;
UPDATE `creature_template` SET `health_mod` = @DRAGONS_BASE_HEALTH + (@DRAGONS_BASE_HEALTH * 0) WHERE `entry` IN (@DRAGON1, @DRAGON2, @DRAGON3);

/* MALYGOS */
SET @MALYGOS_BASE_HP_MODIFIER:= 1400;
SET @MALYGOS_25_ENTRY:= 31734;
SET @MALYGOS_BASE_HP_MODIFIER_10:= 500;
SET @MALYGOS_10_ENTRY:= 28859;

UPDATE `creature_template` SET `Health_mod` = @MALYGOS_BASE_HP_MODIFIER + (@MALYGOS_BASE_HP_MODIFIER * 0) WHERE `entry` = @MALYGOS_25_ENTRY;
UPDATE `creature_template` SET `Health_mod` = @MALYGOS_BASE_HP_MODIFIER_10 + (@MALYGOS_BASE_HP_MODIFIER_10 * 0) WHERE `entry` = @MALYGOS_10_ENTRY;

SET @NEXUS_LORD_HP_BASE_MODIFIER:= 45;
SET @NEXUS_LORD_25_ENTRY:= 31750;
SET @NEXUS_LORD_10_ENTRY:= 30245;

SET @NEXUS_LORD_BASE_DMG_10:= 17;
SET @NEXUS_LORD_BASE_DMG_25:= 35;

UPDATE `creature_template` SET `Health_mod` = @NEXUS_LORD_HP_BASE_MODIFIER + (@NEXUS_LORD_HP_BASE_MODIFIER * 0), `dmg_multiplier` = @NEXUS_LORD_BASE_DMG_25 WHERE `entry` = @NEXUS_LORD_25_ENTRY;
UPDATE `creature_template` SET `dmg_multiplier` = @NEXUS_LORD_BASE_DMG_10 WHERE `entry` = @NEXUS_LORD_10_ENTRY;

SET @SCION_OF_ETERNITY_HP_BASE_MODIFIER:= 30;
SET @SCION_OF_ETERNITY_25_ENTRY:= 31751;

UPDATE `creature_template` SET `Health_mod` = @SCION_OF_ETERNITY_HP_BASE_MODIFIER + (@SCION_OF_ETERNITY_HP_BASE_MODIFIER * 0) WHERE `entry` = @SCION_OF_ETERNITY_25_ENTRY;

SET @POWER_SPARK_25_BASE_HP:= 3;
SET @POWER_SPARK_10_BASE_HP:= 1;

SET @POWER_SPARK_25:= 32187;
SET @POWER_SPARK_10:= 30084;

UPDATE `creature_template` SET `health_mod` = @POWER_SPARK_10_BASE_HP WHERE `entry` = @POWER_SPARK_10;
UPDATE `creature_template` SET `health_mod` = @POWER_SPARK_25_BASE_HP WHERE `entry` = @POWER_SPARK_25;

SET @MALYGOS_10_BASE_DMG_MULTIPLIER:= 25;
SET @MALYGOS_25_BASE_DMG_MULTIPLIER:= 50;

UPDATE `creature_template` SET `dmg_multiplier` = @MALYGOS_10_BASE_DMG_MULTIPLIER WHERE `entry` = @MALYGOS_10_ENTRY;
UPDATE `creature_template` SET `dmg_multiplier` = @MALYGOS_25_BASE_DMG_MULTIPLIER WHERE `entry` = @MALYGOS_25_ENTRY;
