UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'die';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'respawn';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'damage';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify hp';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify mana';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify rage';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify runicpower';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify energy';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify speed';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'additem';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'modify reputation ';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'learn';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'cast';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'aura';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'debug bg';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'debug arena';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'tele';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'appear';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'summon';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'gm';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'gm fly';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'combatstop';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'groupsummon';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'instance unbind';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` LIKE '%lookup%';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'gps';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'npc info';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'quest add';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'quest complete';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'quest reward';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'quest remove';
UPDATE `command` SET `security` = '0' WHERE `command`.`name` = 'unaura';