DROP TABLE IF EXISTS `bazar_auction`;

CREATE TABLE `bazar_auction` (
  `auctionId` int(10) unsigned NOT NULL DEFAULT '0',
  `account_id` int(10) unsigned NOT NULL DEFAULT '0',
  `char_guid` int(10) unsigned NOT NULL DEFAULT '0',
  `mo_amount` int(10) unsigned NOT NULL DEFAULT '0',
  `dp_amount` int(10) unsigned NOT NULL DEFAULT '0',
  `auction_type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `owner_name` varchar(30) NOT NULL DEFAULT '',
  `slave_race` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_class` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_gender` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_money` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_arena` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_honor` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_riding` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_mainspec` varchar(30) NOT NULL DEFAULT '',
  `slave_offspec` varchar(30) NOT NULL DEFAULT '',
  `slave_avgitemlevel` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot1` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot2` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot3` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot4` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot5` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot6` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot7` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot8` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot9` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot10` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot11` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot12` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot13` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot14` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot15` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot16` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot17` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot18` int(10) unsigned NOT NULL DEFAULT '0',
  `slave_level_slot19` int(10) unsigned NOT NULL DEFAULT '0',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`auctionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;