DROP TABLE IF EXISTS `log_loot`;

CREATE TABLE `log_loot` (
	`map_id` INT(10) UNSIGNED NOT NULL,
	`instance_id` INT(10) UNSIGNED NOT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`owner_entry` INT(10) UNSIGNED NOT NULL,
	`item_entry` INT(10) UNSIGNED NOT NULL,
	`looter_guid` INT(10) UNSIGNED NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Log loot';