DROP TABLE IF EXISTS `creature_records`;
CREATE TABLE `creature_records` (
	`entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`CreatureName` VARCHAR(100) NOT NULL DEFAULT '',
	`BestKillTime` MEDIUMINT(10) UNSIGNED NOT NULL DEFAULT '0',
	`RealmFirstGuild` VARCHAR(24) NOT NULL DEFAULT '',
	`BestTimeGuild` VARCHAR(24) NOT NULL DEFAULT '',
	`PrevBestTimeGuild` VARCHAR(24) NOT NULL DEFAULT '',
	PRIMARY KEY (`entry`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;
