DROP TABLE IF EXISTS opcodes_cooldown;
CREATE TABLE `opcodes_cooldown`(
`opcode` VARCHAR(40) NOT NULL COMMENT 'Opcode name',
`cooldown` INT(4) UNSIGNED DEFAULT '1000' COMMENT 'Opcode cooldown',
PRIMARY KEY (`opcode`)
);

INSERT INTO `opcodes_cooldown` VALUES
('CMSG_WHO', 5000),
('CMSG_ADD_FRIEND', 3000),
('CMSG_GROUP_INVITE', 1500),
('CMSG_INSPECT', 5000),
('CMSG_GROUP_CHANGE_SUB_GROUP', 1000),
('CMSG_GUILD_BANK_SWAP_ITEMS', 3000);
